apps/loginreg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register$', views.register, name="register"),
    url(r'^login$', views.login, name="login"),
    url(r'^success$', views.success, name="success")
]

login_and_registration/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.loginreg.urls', namespace="loginreg"))
]

apps/loginreg/models.py
from __future__ import unicode_literals
from django.db import models
import re, bcrypt

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def login(self, postData):
        errors = []
        modelResponse = {}
        user = Users.objects.filter(email=postData["email"])
        if len(user) < 1:
            errors.append("That email doesn't exist")
        else:
            if bcrypt.checkpw(postData["password"].encode(), user[0].password.encode()):
                modelResponse["loggedin"] = True
                modelResponse["user"] = user[0]
            else:
                errors.append("Password is incorrect")
        if errors:
            modelResponse["loggedin"] = False
            errors.append("Please try logging in again")
            modelResponse["errors"] = errors
        return modelResponse

    def register(self, postData):
        noErrors = True
        errors = []
        modelResponse = {}
        if len(postData["first_name"]) < 2:
            errors.append("First name needs to be greater than 2 letters.")
            noErrors = False
        if len(postData["last_name"]) < 2:
            errors.append("Last name needs to be greater than 2 letters.")
            noErrors = False
        if len(postData["password"]) < 2:
            errors.append("Password needs to be greater than 2 letters.")
            noErrors = False
        if not EMAIL_REGEX.match(postData['email']):
            errors.append("Not a validito email address.")
            noErrors = False
        if len(postData["password"]) < 8:
            errors.append("Password needs to be at least 8 characters long")
            noErrors = False
        if postData["password"] != postData["confirm-pw"]:
            errors.append("Passwords don't match.")
            noErrors = False
        if noErrors:
            modelResponse["registered"] = True
            pw_hash = bcrypt.hashpw(postData["password"].encode(), bcrypt.gensalt())
            modelResponse["user"] = Users.objects.create(first_name=postData["first_name"], last_name=postData["last_name"],email=postData["email"],password=pw_hash)
        else:
            modelResponse["registered"] = False
            errors.append("Please try registering again")
            modelResponse["errors"] = errors
        return modelResponse

class Users(models.Model):
  first_name = models.CharField(max_length=45)
  last_name = models.CharField(max_length=45)
  email = models.CharField(max_length=100)
  password = models.CharField(max_length=255)
  created_at = models.DateTimeField(auto_now_add = True)
  updated_at = models.DateTimeField(auto_now = True)

  objects = UserManager()

apps/loginreg/views.py
from django.shortcuts import render, redirect
from .models import Users
from django.contrib import messages

def index(request):
    # Users.objects.all().delete()
    context = {
        "users": Users.objects.all()
    }
    return render(request, "loginreg/index.html", context)

def register(request):
    if request.method == "POST":
        modelResponse = Users.objects.register(request.POST)
        if modelResponse["registered"]:
            print "yay"
            request.session["id"] = modelResponse["user"].id
            request.session["first_name"] = modelResponse["user"].first_name
            request.session["last_name"] = modelResponse["user"].last_name
            request.session["welcome_message"] = "registered."
            return redirect("loginreg:success")
        else:
            for error in modelResponse["errors"]:
                messages.error(request, error)
            return redirect("loginreg:index")

def login(request):
    if request.method == "POST":
        modelResponse = Users.objects.login(request.POST)
        if modelResponse["loggedin"]:
            request.session["id"] = modelResponse["user"].id
            request.session["first_name"] = modelResponse["user"].first_name
            request.session["last_name"] = modelResponse["user"].last_name
            request.session["welcome_message"] = "logged in."
            return redirect("loginreg:success")
        else:
            for error in modelResponse["errors"]:
                messages.error(request, error)
            return redirect("loginreg:index")

def success(request):
    return render(request, "loginreg/success.html")

apps/loginreg/templates/loginreg/index.html
<!-- <!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <title>Login and Registration</title>
    <link rel="stylesheet" href="{% static 'loginreg/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'loginreg/css/loginreg.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    </script>
    <script type="text/javascript">
      "use strict";
      $(document).ready(function() {
          $('#login-form-link').click(function(e) {
      		$("#login-form").delay(100).fadeIn(100);
       		$("#register-form").fadeOut(100);
      		$('#register-form-link').removeClass('active');
      		$(this).addClass('active');
      		e.preventDefault();
      	});
      	$('#register-form-link').click(function(e) {
      		$("#register-form").delay(100).fadeIn(100);
       		$("#login-form").fadeOut(100);
      		$('#login-form-link').removeClass('active');
      		$(this).addClass('active');
      		e.preventDefault();
      	});
      });
    </script>
  </head>
  <body>
    <div class="container">
    	<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="panel panel-login">
					<div class="panel-heading">
						<div class="row">
							<div class="col-xs-6">
								<a href="#" class="active" id="login-form-link">Login</a>
							</div>
							<div class="col-xs-6">
								<a href="#" id="register-form-link">Register</a>
							</div>
						</div>
						<hr>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-12">
								<form action="{% url 'loginreg:login' %}" method="post" id="login-form" action="http://phpoll.com/login/process" method="post" role="form" style="display: block;">
                  {% csrf_token %}
									<div class="form-group">
										<input type="text" name="email" id="username" tabindex="1" class="form-control" placeholder="Email" value="">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="login" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Log In">
											</div>
										</div>
									</div>
								</form>
								<form action="{% url 'loginreg:register' %}" method="post" id="register-form" action="http://phpoll.com/register/process" method="post" role="form" style="display: none;">
                  {% csrf_token %}
									<div class="form-group">
										<input type="text" name="first_name" id="username" tabindex="1" class="form-control" placeholder="First Name" value="">
									</div>
                  <div class="form-group">
                    <input type="text" name="last_name" id="username" tabindex="1" class="form-control" placeholder="Last Name" value="">
                  </div>
									<div class="form-group">
										<input type="email" name="email" id="email" tabindex="1" class="form-control" placeholder="Email Address" value="">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
									</div>
									<div class="form-group">
										<input type="password" name="confirm-pw" id="confirm-password" tabindex="2" class="form-control" placeholder="Confirm Password">
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Register">
											</div>
										</div>
									</div>
								</form>
                <ul>
                {% if messages %}
                  {% for message in messages %}
                    <li style="color:red"> {{message}} </li>
                  {% endfor %}
                {% endif %}
                </ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
  </body>
  <h1>*****Testing******</h1>
  <ul>
  {% for user in users%}
    <li>
    {{ user.id }},
    {{ user.first_name }}
    {{ user.last_name }},
    {{ user.password }}
    </li>
  {% endfor %}
  </ul>
</html> -->

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Registration</h1>
    <form action="{% url 'loginreg:register' %}" method="post">
      {% csrf_token %}
      <label>
        First Name: <input type="text" name="first_name" value="">
      </label>
      <label>
        Last Name: <input type="text" name="last_name" value="">
      </label>
      <label>
        Email: <input type="text" name="email" value="">
      </label>
      <label>
        Password: <input type="text" name="password" value="">
      </label>
      <label>
        Confirm Password: <input type="text" name="confirm-pw" value="">
      </label>
      <input type="submit" name="register" value="Register">
    </form>
    <h1>Login</h1>
    <form action="{% url 'loginreg:login' %}" method="post">
      {% csrf_token %}
      <label>
        Email: <input type="text" name="email" value="">
      </label>
      <label>
        Password: <input type="text" name="password" value="">
      </label>
      <input type="submit" name="login" value="Login">
    </form>
    <h1>*****Testing******</h1>
    <ul>
    {% for user in users%}
      <li>
      {{ user.id }},
      {{ user.first_name }}
      {{ user.last_name }},
      {{ user.password }}
      </li>
    {% endfor %}
    </ul>
  </body>
</html>

apps/loginreg/templates/loginreg/loginreg_plain.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Registration</h1>
    <form action="/register" method="post">
      {% csrf_token %}
      <label>
        First Name: <input type="text" name="first_name" value="">
      </label>
      <label>
        Last Name: <input type="text" name="last_name" value="">
      </label>
      <label>
        Email: <input type="text" name="email" value="">
      </label>
      <label>
        Password: <input type="text" name="password" value="">
      </label>
      <label>
        Confirm Password: <input type="text" name="confirm-pw" value="">
      </label>
      <input type="submit" name="register" value="Register">
    </form>
    <h1>Login</h1>
    <form action="/login" method="post">
      {% csrf_token %}
      <label>
        Email: <input type="text" name="email" value="">
      </label>
      <label>
        Password: <input type="text" name="password" value="">
      </label>
      <input type="submit" name="login" value="Login">
    </form>
    <ul>
    {% for user in users%}
      <li>
      {{ user.id }},
      {{ user.first_name }}
      {{ user.last_name }},
      {{ user.password }}
      </li>
    {% endfor %}
    </ul>
  </body>
</html>

apps/loginreg/templates/loginreg/success.html
<!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'loginreg/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'loginreg/css/loginreg.css' %}">
    <title>Success</title>
  </head>
  <body>
    <div class="form-group">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <h1>Success</h1>
          <h2>{{request.session.first_name}} {{request.session.last_name}} has successfully {{ request.session.welcome_message }}</h2>
        </div>
      </div>
    </div>
  </body>
</html>